title: 테딩의 포트폴리오사이트
name: 서태원
email: seotae89@gmail.com
description: >-
  Data Scientist & A.I developer


baseurl: ""
url: "https://taeding.github.io"


# profile 이미지
profile_image: images/me.jpg


# SNS 아이디
facebook_id: taewon.seo.92
instagram_id: seotae


# Youtube vid
youtube_vid: #


# Custom Color
primary: 2c98f0 #b72cf0
primary_hover: 44A4F2 #9a2dc7
color_1: 2c98f0 #b72cf0
color_2: ec5453
color_3: f9bf3f
color_4: a84cb8
color_5: 2fa499
color_6: 4054b2


# slider type 0  (텍스트가 우측 정렬된 슬라이더)
slider_0: # 형식에 맞추어 항목 추가
- background_url: images/yanggon_bg1.JPG
  title: 안녕하세요. <br>반갑습니다!</br>
  position: absolute
  transform: translate( -50%, -50% )
  left: -170px
  bottom: 650px

# slider type 1  (텍스트가 좌측 정렬된 슬라이더)
slider_1: # 형식에 맞추어 항목 추가
- background_url: images/meteora.png
  title: Taewon portfolio site
  subtitle: >-
    조금은 늦었지만<br>
    아무것도 몰랐지만<br>
    긍정적인 마인드로 성장중인<br>
    초보 개발자 입니다.
  position: absolute
  transform: translate( -50%, -50% )
  left: 650px
  bottom: -100px


# slider type 2  
slider_2: # 형식에 맞추어 항목 추가
- background_url: images/snowboarding.png
  title: I am<br>AI Developer
  subtitle: >-
    다양한 경험을 하였고<br>
    여행 및 레저를 즐기며<br>
    꿈을 향해 노력중입니다.
  position: absolute
  transform: translate( -50%, -50% )
  left: 200px
  bottom: -100px


# About
about_meta: About Me
about_header: >- 
  "행복을 찾는 AI탐험가 서태원입니다."
about_introduce: >-
  "안녕하세요. 여러가지 경험을 쌓고 AI전문가가 되기위해 노력하고 있습니다."
about_content: >-
  AI에 관심이 생기게 된 계기는 이세돌9단과 알파고와의 바둑대결을 보고 처음 생겼습니다.<br>
  그 당시에는 막연하게 인공지능이 바둑을 둘 정도가 되었다면, 이제는 정말 모든 걸 해줄 수 있겠다는 생각이 들었습니다. <br>
  회사 생활 중 ERP시스템을 ORACLE에서 SAP로 전환하는 시기가 맞물렸었는데, 그 당시에 회사 전반적인 시스템에 대하여 많이 배울 수 있었습니다.<br>
  그때 느꼈던 것이 AI가 정말 고도화된다면, 제조업의 경우 많은 인력을 줄여 소수의 인원으로도 업무를 처리하는 것이 가능할 정도로 자동화 시스템을 구축할 수 있겠다고 생각했습니다.<br>
  과거 데이터가 축적되어 매출에 따른 재고관리, 그에 따른 부족한 자재 발주와 예상 판매량, 실질적 매출에 따른 회계장부 처리 등 말입니다.<br>
  제조업에 국한되지 않고 일상생활에서도 알고리즘 등을 이용해 데이트코스 추천 등 사람들이 결정함에 있어 스트레스를 받는 분야라면 AI가 큰 힘이 될 것이라 생각합니다.<br>
  <strong>비전공자이기 때문에 그만큼 스스로의 부족함을 인지하고 더 열심히 노력할 것입니다.</strong>
  성장 중인 AI탐구자로서 전문가가 되기 위해 노력하고 있습니다.
about_services: # 형식에 맞추어 항목 추가
- icon: icon-data
  name: Data
- icon: icon-monitor
  name: AI
- icon: icon-database
  name: DB
- icon: icon-code
  name: Python
about_box_content: 
  ＂사람은 태어나서 죽을 때까지 평생 공부해야 한단다.＂ <br><br>
  할아버지의 가르침이 처음에는 당연한 것이라 생각했지만, <br>
  그것이 얼마나 어려운 일인지 체감하고 있습니다.<br> <b>학습</b>을 게을리하지 않을 것입니다.

about_box_content_color : rgb(255,255,255)

about_box_button:
  link: https://github.com/hotelbread
  name: Pro가 되기위해 항상 노력할 것입니다.

# Tech  skill
tech_meta: TECH SKILLS
tech_header: 저는 현재 이것을 할 수 있습니다.
tech_content:
 멋쟁이사자처럼 교육을 들으며<br> 
 1. 파이썬문법부터 시작하여<br>
 2. 전통적인 머신러닝 기법<br>
 3. 딥러닝 기법<br>
 4. DB의 SQLite기본 사용법<br>
 5. 웹크롤링<br>
 등을 학습하였습니다.
tech_list: # 형식에 맞추어 항목 추가
- name: Python
  color: color-1
  animation: fadeInLeft
  percent: 60
  mark: 60
  content: 파이썬 기초, 데이터 분석과 시각화를 공부하고 파이썬 언어의 기본적인 문법에 대해 알고 있으며, 자료구조 및 알고리즘을 파이썬으로 공부하였습니다.
- name: 머신러닝
  color: color-2
  animation: fadeInRight
  percent: 40
  mark: 40
  content: 전통적인 머신러닝의 기법 및 이론을 공부하였습니다.<br> 추가적으로 프로젝트를 통해 실습을 해보았습니다. <br>
- name: 딥러닝
  color: color-3
  animation: fadeInLeft
  percent: 30
  mark: 30
  content: 공부하면 공부할수록 이 분야가 정말 방대하고 제가 아는것이 정말 일부분이라는 것을 많이 느낍니다. CV분야 실습을 위해 모바일넷 활용도 프로젝트를 통해 구현해 보았습니다.
- name: DB
  color: color-5
  animation: fadeInLeft
  percent: 20
  mark: 20
  content: 교육간 매우 기초적인 부분만 배운상태입니다.<br> 교육 수료생 동기와 스터디를 통해 다시 공부할 예정입니다.
- name: Github
  color: color-4
  animation: fadeInRight
  percent: 20
  mark: 20
  content: github서버를 활용하여 블로그 및 포트폴리오 사이트를 관리를 시작한 단계입니다. 아직 github를 통해 소스코드를 관리하거나 협업한 경험은 없어 배울점이 많이 남아 있습니다. 

tech_desc: 앞으로는 회사에서 요구하는 분야는 물론 <strong> Github, python, 머신러닝, 딥러닝 추가적으로 Javascript </strong>등을 계속해서 공부하여 발전해 나갈 생각입니다.


# Project
project_meta: My Work
project_header: PROJECT
project_introduce: 
  저의 Project를 소개합니다.

# 더보기 내용
project_load_more: 앞으로 더 많은 프로젝트가 추가될 예정입니다:)
project_load_more_url: https://github.com/hotelbread

project_my_name: Mid & Final project

project_my: # 형식에 맞추어 항목 추가
- background_url: images/mid_project_team4_oliveyoung.jpg
  animation: fadeInLeft
  name: 소비자가 원하는 화장품 추천시스템
  description: 화장품에 관심 없던 사람, 그리고 명확하게 자신의 피부 고민 및 사용하고 있는 제품이 있는 소비자에게 새로운 제품을 추천하는 시스템입니다. <br> 1. 사용하고 있는 제품과 유사한 제품을 리뷰를 통해 추천<br> 2. 자신의 피부 고민을 적으면 제품 리뷰 기반으로 알맞은 제품 추천
  detail_url: #
  readmore_url: pdf/team4_oliveyoung.pdf

- background_url: images/final_project_pic.png
  animation: fadeInLeft
  name: 소비자가 원하는 와인 추천시스템
  description: 새로운 와인을 즐기고 싶은 사람, 혹은 시도해 보고 싶었지만 와인 종류가 너무 많아 망설였던 소비자에게 알맞은 와인을 추천하는 시스템입니다.<br> 1. 자신이 좋아하는 와인이름, 본인이 술을 고를때 중요시하는 factor의 가중치 입력을 통한 추천<br> 2. 소비자가 와인을 고를 때 어떤 점을 주안점으로 두는지 조금 더 명확한 데이터를 받아 와인을 추천 ex)가격범위, 도수범위, 생산국가 등<br> 3. 고객이 안주상을 사진으로 찍으면, 그 사진에 나오는 음식이 어떤 음식인지 인식해 그와 어울리는 와인을 추천
  detail_url: #
  readmore_url: pdf/wine_recommend.pdf

project_team_name: Semi-project
project_team: # 형식에 맞추어 항목 추가
- background_url: images/titanic_semi.png
  animation: fadeInRight
  name: Titanic 생존자 예측
  description: Kaggle의 대표적인 문제인 Titanic 생존자 예측 문제를 교육간 semi-project로 해결해 보았습니다.
  detail_url: #
  readmore_url: #

- background_url: images/airlinepassengersatisfaction.png
  animation: fadeInRight
  name: 비행승객 만족도 분석 Airline Passenger Satisfaction
  description: Kaggle의 Airline Passenger Satisfaction 문제를 교육간 semi-project로 해결해 보았습니다.
  detail_url: #
  readmore_url: pdf/airline_satisfaction.pdf

- background_url: images/cctv_semiproject.png
  animation: fadeInRight
  name: 서울시 가 구별 뺑소니 건수와 CCTV 설치 개수와의 연관성 분석
  description: >-
   교육을 들으며 진행한 첫 semi-project로써 CCTV가 많을수록 뺑소니 건수가 적을 것이라는 가정하에 진행된 프로젝트였습니다.
   <br> 데이터 수집부터 가공, 지도에 시각화를 하는 방법을 공부할 수 있었습니다.
   <br> 분석결과 CCTV 설치 개수와 뺑소니 발생건수는 피어슨 상관관계분석 결과 약한 양의 상관관계에 있다는 것을 확인하였습니다.
  detail_url: #
  readmore_url: pdf/cctv_semi.pdf

# project_business_name: Semi-project
# project_business: # 형식에 맞추어 항목 추가
# - background_url: images/cctv_semiproject.png
#   animation: fadeInTop
#   name: 서울시 가 구별 뺑소니 건수와 CCTV 설치 개수와의 연관성 분석
#   description: >-
#    교육을 들으며 진행한 첫 semi-project로써 CCTV가 많을수록 뺑소니 건수가 적을 것이라는 가정하에 진행된 프로젝트였습니다.
#    <br> 데이터 수집부터 가공, 지도에 시각화를 하는 방법을 공부할 수 있었습니다.
#    <br> 분석결과 CCTV 설치 개수와 뺑소니 발생건수는 피어슨 상관관계분석 결과 약한 양의 상관관계에 있다는 것을 확인하였습니다.
#   detail_url: #
#   readmore_url: #


# Experience
exp_meta: What have I achieved?
exp_header: 저는 이런 "경험"들을 해봤습니다.
exp_content: 다양한 경험을 통해 다재다능한 역량을 보유하고 있습니다.
exp_services: # 형식에 맞추어 항목 추가
- name: leadership
  color: color-1
  icon: icon-bulb
  content: 군복무를 ROTC를 통해 장교생활을 하며 리더쉽을 함양할 수 있었습니다.<br>
- name: 다양한 경험
  color: color-2
  icon: icon-home
  content: 전역 이후 Ireland로 워킹홀리데이를 다녀온 경험<br>글로벌 기업 영업1팀에서 회사생활을 한 경험이 있습니다.
- name: 배움에 대한 열정
  color: color-3
  icon: icon-phone3
  content: 제가 선택한 길, 항상 열정을 다해 공부하며 새로운 기술에 대해 즐거운 마음으로 배웁니다.
- name: 다양한 취미활동
  color: color-5
  icon: icon-flash
  content: 여름에는 수영과 서핑, 겨울에는 스노우보드. 최근에는 테니스 등 다양한 운동을 하여 조직생활에 잘 융화됩니다.
exp_counters:
# - name: Online Class Sales
#   count: 344
#   speed: 10000
- name: project
  count: 5
  speed: 5000


# Career
carerr_meta: career
career_header: Work Career
career_list:
- name: ORDEG
  date: 2018.08 ~ 2019.09
  content: <strong>ORDEG은 UMICORE의 자회사로 주로 자동차 촉매를 생산하여 완성차 업체에 납품하는 사업을 주 업무로 하는 회사입니다.</strong><br> -영업1팀 소속으로서 저는 Supply Chain 관리 및 매출 관리 업무를 하였습니다. 촉매의 단가가 고가였었기 때문에 일반적인 도급계약이 아닌 사급거래를 통해 매출이 발생하여 Customer인 완성차 업체와 물품을 납품하게 되는 Canner사 사이에서 발생하는 차이를 없애고, 매월 마감업물 진행하여 Sales Report를 작성하였습니다. 추가적으로 양산차용 외의 촉매로 파이롯트에 들어가는 Sample의 수량 및 납기일 등을 전반적으로 조율하며 관리하였습니다.
  #  ORDEG은 벨기에의 UMICORE 자회사로 자동차촉매 업체입니다. <br> 영업1팀에서 영업관리 업무를 했습니다. <br> Supply chain관리 및 pilot제품의 납기 전반적인 일정을 조율 하였고, 매달 영업 매출 마감업무를 진행 후 sales report를 작성하였습니다.
  color: color-1
  icon: icon-pen2
  animation: fadeInLeft
- name: STARBUCKS, kokoro sushi bento in Dublin
  date: 2017.01 ~ 2017.06
  content: 아일랜드 워킹홀리데이를 가서 어학연수로 어학당을 다닌 이후에 스시팩토리와 스타벅스에서 일을 해보았습니다.
  color: color-2
  icon: icon-pen2
  animation: fadeInRight
- name: ROTC 육군 포병장교 출신
  date: 2013.03 ~ 2015.06
  content: 육군 장교로서 포병대대에서 관측장교, 교육장교 임무수행
  color: color-3
  icon: icon-pen2
  animation: fadeInLeft


# Education
edu_meta: Education
edu_header: Education
edu_list:
- title: Department of Convergence Standard Policy at Chung-Ang University Graduate School of Public Administration
  subtitle: 중앙대 행정대학원 융복합표준정책학과
  date: 2021.03 - 휴학 中
  content: 표준정책관련하여 공부를 했었습니다. 현재는 휴학 중입니다.
- title: HONGIK UNIVERSITY MECHANICAL SYSTEM DESIGN ENGINEERING
  subtitle: 홍익대학교 기계시스템디자인공학과 졸업
  date: 2009.03 - 2013.02
  content: 기계설계과라고 이해하시면 됩니다. 학부과정이라 기계공학과와 같습니다.
- title: KONGJU NATIONAL UNIVERSITY HIGH SCHOOL
  subtitle: 공주대학교 사범대학 부설고등학교
  date: 2005.03 - 2008.02
  content: >-
    부모님의 건강 악화로 집에서 학업을 이어갈 수 없는 상황에서 중학교 성적이 우수하였기에 지방 기숙사 명문고등학교 진학하게 되었습니다.


# Blog
blog_meta: self-improvement
blog_header: BLOG
blog_load_more: 더 발전하기 위해 항상 노력합니다    # 더보기 내용
blog_load_more_url: https://hotelbread.github.io
blog_list:
- title: 행복을 찾는 AI 탐험가 테딩의 블로그
  subtitle: 개인 블로그 운영
  date: 2022.01
  content: 일상적인 내용과, 여러 인공지능 관련된 내용의 포스팅을 하기위해 블로그를 개설해 보았습니다.
  thumbnail_url: images/blogpage_taeding.png
  link: https://hotelbread.github.io
# - title: #
#   subtitle: #개발,논문 유튜브 채널 운영
#   date: #2018.04
#   content: #유튜브 채널을 운영하며 배운 것들을 정리해서 영상을 촬영하고 있습니다. 개인적으로 복습을 한번 더 하는 장점이 있습니다.
#   thumbnail_url: #images/blog-2.PNG
#   link: #
# - title: #네이버블로그
#   subtitle: #이전 블로그
#   date: #2018.03
#   content: #막 복학을하고 전과했을때 시작했던 첫블로그입니다.
#   thumbnail_url: #images/blog-3.PNG
#   link: #


# Contact
contact_meta: Get in Touch
contact_header: Contact
contact_list:
- title: seotae89@gmail.com
  icon: icon-globe-outline
- title: 경기도 부천시 신흥로 276번길 15, 103-904
  icon: icon-map
- title: +82 10 7576 5640
  icon: icon-phone
- title: 웹 주소
  icon: icon-layers2
  url: https://github.com/hotelbread
contact_message: <em>연락해주셔서 감사합니다.</em> 24시간이내에 회신드리도록 하겠습니다. :)


optional_front_matter:
  remove_originals:    true
